apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: griecoengineering-net-tls
spec:
    secretName: griecoengineering-net
    issuerRef:
        name: letsencrypt-prod
        kind: CluserIssuer
    commonName: griecoengineering.net
    dnsnames:
        - griecoengineering.net
        - www.griecoengineering.net
    acme:
        - http01:
            ingressClass: nginx
        domains>
            - griecoengineering.net
            - www.griecoengineering.net 